remote_theme: "jekyll/minima@1e8a445"
title: **R2PM'27 - 1st International Workshop on Robust and Resilient Process Mining**
description: 1st Internation Workshop on Robust and Resilient Process Mining
