remote_theme: "jekyll/minima@1e8a445"
title: 1st International Workshop on Robust and Resilient Process Mining, co-located with ICPM'27
description: 1st Internation Workshop on Robust and Resilient Process Mining
